/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docSidebar:[
    'rm2023',
    'welcome',
    'learning_path',
    {
      'Foundation':
      [{
        CPP:
        [
          'cpp_01',
          'cpp_03',
        ],
        Ubuntu:
        [
          'about_ubuntu',
          'ubuntu_install_vm',
          'ubuntu_install_dual',
          'ubuntu_00',
          'ubuntu_01',
          'ubuntu_02',
          'ubuntu_03',
          'ubuntu_04',
          'linux_01',
        ],
        ROS:
        [
          'ros_install',
          'ros_foundation'
        ],
        Cmake:
        [
          'gcc_g++',
          'cmake',
          'catkin',
        ]
      },],
    },
    'others',
  ],
  examSidebar:[{
    'Exam':
    [
      'exam_cpp',
      'exam_ros',
      'practice_01',
    ],
  },],
  repoSidebar:[
    'sim_rmua',
    'lableimg',
  ],


  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Docs',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],

};

module.exports = sidebars;
